name = "voice-standup"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://horancheng.github.io"

[[kv_namespaces]]
binding = "STANDUPS"
id = "a69759f73c67454f9ccd3c296915a6ea"
